FROM debian:latest

RUN apt-get update -qq &&\
    apt-get install -y build-essential libncurses5-dev gawk git subversion \
        libssl-dev gettext zlib1g-dev swig unzip python2.7 wget file &&\
        apt-get -y autoremove && apt-get clean

RUN useradd -c "OpenWrt Builder" -m -d /home/build -s /bin/bash build
COPY --chown=build:build ./imagebuilder /home/build/imagebuilder
RUN chown build:build /home/build/imagebuilder

USER build
ENV HOME /home/build
WORKDIR /home/build/imagebuilder
