FROM openwrt/sdk

MAINTAINER Nick Hainke <vincent@systemli.org>

LABEL "com.github.actions.name"="OpenWrt SDK (XDP)"

USER root

RUN apt-get update -qq &&\
    apt-get install -y \
        clang \
        llvm \
        && apt-get -y autoremove \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/*

USER build
